feat: address transformation
NHSDigital/dtos-cohort-manager pull request #118
Opened 2024-08-06 14:23 UTC by will-larkin-nhs

## Description

- added address transformation feature
- documentation
- refactored transform data service 
- added an overloaded constructor to `Model.Participant` to allow for easy conversion from `CohortDistributionParticipant`

## Context
[DTOSS-3496](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3496)

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [x] I have added tests to cover my changes
- [x] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-08-06 14:29 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +                            throw new ArgumentException();
why are you doing this?

2024-08-06 14:29 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Model/Participant.cs
> +    public Participant(CohortDistributionParticipant cohortDistributionParticipant) {
can you put this opening bracket on a new line please?

2024-08-06 14:45 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +                            throw new ArgumentException();
Ticket says so

2024-08-06 14:48 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +                            throw new ArgumentException();
I don't like throwing exceptions in code outside of a catch block. I would break out of the while loop here and return a null participant and then in the main body of this function possibly return an bad request and that way we can handle the error more normally

2024-08-06 14:49 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +                            throw new ArgumentException();
it is temporary, will use the exception service in the future

2024-08-06 14:57 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +                            throw new ArgumentException();
that m makes sense, I am still not keen on throwing an exception outside of a catch block, I there will be a better way of doing this

2024-08-09 08:28 UTC, MWClayson-NHS requested changes
One the Database issues are resolved i'll approve. everything else looks good to me.

2024-08-09 08:28 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +                        $"WHERE PARTICIPANT_ID = '{participant.ParticipantId}'";
This is a security risk and could be exploited via SQL Injection . use SQL params to sort this.

2024-08-09 08:28 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +            string sql = $"SELECT POST_CODE, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5 " +
Why are we writing Sql directly in the functions? this should be held centrally in the database stuff in the common function library.

2024-08-13 09:51 UTC, will-larkin commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +            string sql = $"SELECT POST_CODE, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5 " +
It is only used in this method though and it is not reusable so I have put it in the method to reduce complexity. Is there another reason why we would put it in shared other than if it was being used by multiple functions?

2024-08-13 12:07 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +            string sql = $"SELECT POST_CODE, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5 " +
Its keeping the code base consistent having all database stuff on one part of the application. Having tightly coupled code in parts of the application can make refactoring code very challenging. I.e. if we are looking at moving stuff over to entity framework, its easier if we know where all the database code is stored. 

This will also meaning the code  we right should aim to meet some principals 

Separation of concerns - we should separate the database logic from the business logic etc 
Single Responsibility - one class should responsible for one thing

2024-08-16 09:15 UTC, MWClayson-NHS approved these changes
Looks good to me!

2024-08-16 09:15 UTC, merged