feat: docker updates
NHSDigital/dtos-cohort-manager pull request #139
Opened 2024-08-14 12:55 UTC by will-larkin-nhs

## Description
- Added docker env variables
- Added an azurite setup container to create blob containers and put rules in
- Added a script to send a sample file to azurite
- Added current sample files to repo
- Added a profile for dependencies so people with macs can run docker compose  --profile dependencies up

## Context
- Docker broke
- Changes to the transform function meant that rule files have been moved to azurite

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-08-15 20:10 UTC, stephhou commented on application/CohortManager/Set-up/azurite/rules/lookupRules.json
Are we now maintaining two copies of the the rules?

2024-08-15 20:11 UTC, stephhou commented on scripts/config/gitleaks.toml
> +  '''application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.csproj''',
Why are these changes needed in the gitleaks file?

2024-08-18 14:24 UTC, stephhou requested changes
Can you remove the test files? I'm not sure who this solution is aimed at, but testers and devs will probably need to add files that have specific errors in to test their code works. The would often need to provide new files anyway.

We also shouldn't have two copies of the rules files.

Also, who has requested these changes?

2024-08-19 06:33 UTC, will-larkin-nhs commented on scripts/config/gitleaks.toml
> +  '''application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.csproj''',
False positives on Sudip's stuff

2024-08-19 06:35 UTC, will-larkin-nhs commented on application/CohortManager/Set-up/azurite/rules/lookupRules.json
Will remove the ones in the validation service, transform service has not been migrated to azurite yet so I will leave those

2024-08-19 06:40 UTC, will-larkin-nhs commented
> Can you remove the test files? I'm not sure who this solution is aimed at, but testers and devs will probably need to add files that have specific errors in to test their code works. The would often need to provide new files anyway.

I would prefer to leave them in since they are not really harming anyone and it makes things easier, but fine I will remove them.

> Also, who has requested these changes?

No-one, docker broke so needed to fix that. Then I discovered the rules had been moved to azurite so added that stuff as a productivity/ quality of life thing.

2024-08-20 11:32 UTC, will-larkin-nhs commented on application/CohortManager/Set-up/azurite/rules/lookupRules.json
that's where the files should be now, I have removed the duplicates from the validation service

2024-08-20 14:19 UTC, stephhou submitted a review, later dismissed

2024-08-20 14:56 UTC, Warren-Pitterson approved these changes

2024-08-20 14:56 UTC, merged