feat: check participant exception status before adding to cohort distribution
NHSDigital/dtos-cohort-manager pull request #141
Opened 2024-08-16 08:20 UTC by andrewmorris43

## Description
Adds a db lookup to the participant management table, to check if a participant has an `ExceptionFlag`. 

This check happens before the participant is added to the cohort distribution, and that function will only run if there is **_no_** `ExceptionFlag`.

I've also added a new `Exists` constant for use with any data we are expecting to be either "Y" or "N". 

A future PR can update all hardcoded instances of "Y" and "N" to use this new constant throughout the codebase.

## Context
[DTOSS-3510](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3510)

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [x] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-08-16 08:59 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +                _logger.LogError("The participant has an exception. Unable to add to cohort distribution.");
Can we log the NhsNumber or Participant number as well please

2024-08-16 09:03 UTC, Warren-Pitterson commented on tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs
> +    public async Task Run_Should_Return_BadRequest_When_Participant_Has_An_Exception()
Can we change the testMethod to MethodName_WhatIsBeingtested_ExpectedResult Format please

2024-08-16 09:19 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +                _logger.LogError("The participant has an exception. Unable to add to cohort distribution.");
I don't think we should log the NHS number as its PII, log the Participant number as it'll only make sense to someone who has access to the backend.

2024-08-16 09:50 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +                _logger.LogError("The participant has an exception. Unable to add to cohort distribution.");
I've added the participant id into the log message.

2024-08-16 10:19 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +                _logger.LogError("The participant has an exception. Unable to add to cohort distribution.");
yea that makes sense

2024-08-16 10:27 UTC, andrewmorris43 commented on tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs
> +    public async Task Run_Should_Return_BadRequest_When_Participant_Has_An_Exception()
I've updated all the test method names in this file to follow naming convention.

2024-08-16 11:05 UTC, Warren-Pitterson approved these changes

2024-08-18 14:20 UTC, stephhou requested changes

2024-08-18 14:20 UTC, stephhou commented on application/CohortManager/src/Functions/Shared/Model/Constants/Exists.cs
> +    public const string Yes = "Y";
Is it always either Y or N? Just wondering if it can be null at any stage.

2024-08-18 14:20 UTC, stephhou commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +            if (ParticipantHasException(requestBody.NhsNumber))
I'm wondering if this should be raised in the exception table, so that we can see how many participants have not been added to the Cohort. This might be part of the bigger logging and observability conversation

2024-08-19 07:59 UTC, will-larkin-nhs commented on tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs
> +    public async Task RunAsync_EmptyRequestBody_ReturnsBadRequest()
Test names look good but there are a lot of tests here expecting the same result. Can this be parameterised with `[Datarow]` or something?

2024-08-19 08:02 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/Program.cs
> +        DbProviderFactories.RegisterFactory("System.Data.SqlClient", SqlClientFactory.Instance);
Please add the database connection string env variable to the compose.yaml if you are adding new db calls

2024-08-20 08:07 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/Shared/Model/Constants/Exists.cs
> +    public const string Yes = "Y";
This is just a generic constant class that will always just be "Y" or "N". There are existing null checks for the exception flag when we do the db requests.

2024-08-20 08:08 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +            if (ParticipantHasException(requestBody.NhsNumber))
Let me know if you want me to do this work as part of this PR.

2024-08-20 08:11 UTC, andrewmorris43 commented on tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs
> +    public async Task RunAsync_EmptyRequestBody_ReturnsBadRequest()
Yes I see what you mean, a lot of tests are expecting a bad request. I'll take a look at refactoring them

2024-08-20 08:14 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/Program.cs
> +        DbProviderFactories.RegisterFactory("System.Data.SqlClient", SqlClientFactory.Instance);
I've added this now.

2024-08-20 11:15 UTC, andrewmorris43 commented on tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs
> +    public async Task RunAsync_EmptyRequestBody_ReturnsBadRequest()
I've refactored the tests for missing/invalid request body, and missing fields on the request body to use datarows.

2024-08-22 13:43 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/Program.cs
> +        services.AddSingleton<IDbConnection>(provider =>
Right counter to what i've said before can this be changed back to transient and the classes that have IDbConnection injected in to them should also be changed to transient.

2024-08-27 13:29 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/Program.cs
> +        services.AddSingleton<IDbConnection>(provider =>
I've now made these changes.

2024-08-28 08:16 UTC, MWClayson-NHS approved these changes

2024-09-03 10:18 UTC, MWClayson-NHS approved these changes

2024-09-03 11:13 UTC, SamRobinson75684 approved these changes

2024-09-03 11:22 UTC, merged