feat: added interpreter rule in static rules
NHSDigital/dtos-cohort-manager pull request #143
Opened 2024-08-16 13:14 UTC by antoinerubeiz

## Description

Added a new rule in the staticRules.json file that raises an exception if the Interpreter Required field does not contain a 0 or a 1. 

## Context

It adds a necessary rule to the static validation function.

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [x] I have added tests to cover my changes
- [x] I have updated the documentation accordingly
- [x] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-08-16 16:07 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/staticRules.json
> +        "RuleName": "49.InterpreterCheck",
Is there a standard for RuleName? 

All the others seem to be number.PropertyName, 

I'm thinking this should follow the same and be "49.IsInterpreterRequired"

2024-08-18 14:11 UTC, stephhou requested changes
Just putting reminder to add unit tests, per Michael's comments.

2024-08-19 09:47 UTC, antoinerubeiz commented on application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/staticRules.json
> +        "RuleName": "49.InterpreterCheck",
I wasn't sure, but changed it to what you suggested!

2024-08-21 14:44 UTC, andrewmorris43 submitted a review, later dismissed
Looks good to me. No errors when running a smoke test on my machine too.

2024-08-22 10:50 UTC, stephhou submitted a review, later dismissed

2024-08-22 10:58 UTC, Warren-Pitterson approved these changes

2024-08-22 11:00 UTC, merged