feat: Adding Mesh retrieval function
NHSDigital/dtos-cohort-manager pull request #160
Opened 2024-08-22 12:48 UTC by MWClayson-NHS

## Description

Adding the Mesh Mailbox retrieval function 
Adding Git Submodule for dotnet-mesh-client

## Context

Adds the ability to poll the Mesh Mailbox to retrieve data and move it to the inbound blobstorage
[DTOSS-3524](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3524)

## Type of changes

- [ ] Refactoring (non-breaking change)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [X] I have followed the code style of the project
- [X] I have added tests to cover my changes
- [X] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [X] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-08-22 14:15 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs
> +            var result = await _meshToBlobTransferHandler.MoveFilesFromMeshToBlob(messageFilter, _mailboxId,_blobConnectionString,"inbound");
Its running every 5 mins and will not error is there is nothing found in the mailbox.

2024-08-22 14:17 UTC, MWClayson-NHS commented on .github/workflows/stage-1-commit.yaml
fetch depth needs updating here.

2024-08-22 14:32 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs
> +            var result = await _meshToBlobTransferHandler.MoveFilesFromMeshToBlob(messageFilter, _mailboxId,_blobConnectionString,"inbound");
it's logging an error, would It not be best to just log information?

2024-08-22 15:30 UTC, will-larkin-nhs commented on application/CohortManager/compose.yaml
> +      - MeshKeyPassphrase = ${MESHKEYPASSPHRASE}
Can you please update the .env.example with these varaibles along with a hint on where you can get the values?

2024-08-22 15:33 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs
> +                _logger.LogCritical("Error while connecting getting Messages from MESH. ErrorCode: {ErrorCode}, ErrorDescription: {ErrorDescription}",checkForMessages.Error?.ErrorCode,checkForMessage
Should you not be calling the exception service here?

2024-08-22 15:34 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs
> +
Please write some XML docs here

2024-08-22 15:34 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs
> +                _logger.LogCritical("Error while connecting getting Messages from MESH. ErrorCode: {ErrorCode}, ErrorDescription: {ErrorDescription}",checkForMessages.Error?.ErrorCode,checkForMessage
Im not really sure as its not linked to any file or cohort at this point in time 
@stephhou What do you think?

2024-08-22 15:43 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/Program.cs
> +                Password = Environment.GetEnvironmentVariable("MeshPassword"),
Done, Please check, this will probably need changing once we have more details about the MESH environment.

2024-08-22 15:44 UTC, MWClayson-NHS commented on application/CohortManager/compose.yaml
> +      - MeshKeyPassphrase = ${MESHKEYPASSPHRASE}
Done please check.

2024-08-22 16:02 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs
> +
Done, let me know if thats ok.

2024-08-27 11:56 UTC, mrlockstar commented on application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs
> +            if(messagesMoved == 0 && messageCount == 500)
Why is there a maximum number of message that can be in the Azure storage and why is it 500? Would it not make sense to have the messageCount as a variable so it's configurable?  Just curious as to why 500 is the upper limit?

2024-08-27 12:03 UTC, mrlockstar commented on application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs
> +            if(messagesMoved == 0 && messageCount == 500)
Talked to Michael, he explained the scenario, he is going to put a small comment to explain the scenario .

2024-08-28 11:23 UTC, SamRobinson75684 requested changes
it all looks good to me but I don't want to merge it just yet as I am not sure how it will affect azure. We are so close to the getting the test environment working. After we have pushed to azure then I think we just merge this

2024-10-17 12:12 UTC, MacMur85 submitted a review, later dismissed
Code reviewed. Approved.

2024-10-17 13:03 UTC, Warren-Pitterson commented on tests/CaasIntegrationTests/receiveCaasFileTest/ReceiveCaasFileTests.cs
> +                It.Is<It.IsAnyType>((v, t) => v.ToString().Contains("ile name is invalid.")),
Missing F?

2024-10-17 13:03 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs
> +
whitespace

2024-10-17 13:04 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs
> +            }
is this indent correct?

2024-10-17 13:06 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs
> +
whitespace

2024-10-17 13:14 UTC, Warren-Pitterson approved these changes

2024-10-17 13:31 UTC, SamRobinson75684 approved these changes

2024-10-17 13:31 UTC, merged