feat: reason for removal transformations
NHSDigital/dtos-cohort-manager pull request #365
Opened 2024-11-05 14:20 UTC by andrewmorris43

## Description

Changes in this PR include:
- Adds transformation logic for 4 chained rules.
- Rules 1 and 2 perform multiple transformations when failing. Part of the transformation includes a db lookup for a BSO code.
- Rules 3 and 4 trigger an exception to be raised when failing.
- Fixes an existing issue when making multiple transformations.
- Changes all the `transformRules.json` file rules to trigger on failure, rather than on success.
- A few tweaks to do with the new queue functionality to run things locally.

### Notes
- Db lookup logic for transformation rules is due to change, so the implementation here is temporary.
- To successfully test this locally a few other rules need to be tweaked, although I believe some rule changes are required anyway.

## Context
[DTOSS-4771](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4771)
[DTOSS-4573](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4573)
[DTOSS-4574](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4574)
[DTOSS-4576](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4576)
[DTOSS-4577](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4577)

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-11-05 15:58 UTC, Warren-Pitterson approved these changes

2024-11-07 09:48 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +            try
I don't think this try catch block makes much sense as you are calling another method that would also fail if we fail to log the error to the table?

2024-11-07 09:58 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +            try
I'll remove it, cheers

2024-11-08 09:52 UTC, will-larkin-nhs requested changes
Please reverse the change to make the rules trigger on failure instead of success. It has been unanimously decided in the retros that this is the wrong way to do the rules

2024-11-08 09:53 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
> +        "RuleName": "1.ReasonForRemoval.NonFatal",
Please change the names to something more descriptive

2024-11-08 10:26 UTC, andrewmorris43 commented
> Please reverse the change to make the rules trigger on failure instead of success. It has been unanimously decided in the retros that this is the wrong way to do the rules

@will-larkin-nhs I must have missed that retro where that was decided. I would have argued that it makes more sense to have the rules trigger on failure in this scenario. It makes it much easier to just use the built in ExceptionMessage from rules engine to trigger the validation exception log we need.

I can change it back to trigger on success, but that will involve reverting back to my hacky way to trigger an exception log - not ideal! Plus it doesn't seem right to me to trigger an exception on success.

2024-11-08 10:29 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
> +        "RuleName": "1.ReasonForRemoval.NonFatal",
Will have a think for a better name

2024-11-08 10:52 UTC, andrewmorris43 commented
@will-larkin-nhs Ok cheers, I'll revert things.

2024-11-08 11:35 UTC, will-larkin-nhs submitted a review, later dismissed

2024-11-08 12:06 UTC, will-larkin-nhs approved these changes

2024-11-08 14:56 UTC, Warren-Pitterson submitted a review, later dismissed

2024-11-12 10:36 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +            _logger.LogInformation("A transformation rule raised an exception: {ExceptionMessage}", exception.Message);
should this be LogError if it's raised an Exception? and can we pass the exception in as well please

2024-11-12 13:17 UTC, Warren-Pitterson approved these changes

2024-11-12 13:27 UTC, MWClayson-NHS approved these changes

2024-11-12 13:29 UTC, merged