DTOSS 6414 unit test coverage percent increase for addParticipant
NHSDigital/dtos-cohort-manager pull request #514
Opened 2024-12-17 17:26 UTC by Swapnil261188

## Description

Unit test coverage percent increase for addParticipant from 73.63% to 80.00%.

![testCoverageforAddParticipant](https://github.com/user-attachments/assets/bbf228db-b4d3-4dc1-8874-766c3eaee372)

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-12-17 22:24 UTC, Joseph2910 approved these changes

2024-12-18 07:36 UTC, will-larkin-nhs commented
Please add a proper bullet point description of the changes that have been made and in the context section add either a link to the ticket or if there isn't one give some context on why the changes have been requested and what they are trying to accomplish

2024-12-18 07:42 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
> +        _logger.LogInformation("Starting processing of queue message...");
Is this log necessary? Especially when you have 2 log statements below saying the function has been called and deserialization has started.

2024-12-18 07:49 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
> +        _logger.LogInformation("[1] Serializing participant data for validation step 1...");
what is the purpose of all of these logs?

2024-12-18 07:49 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
>              _logger.LogInformation("Eligible: sending record to add at {datetime}", DateTime.UtcNow);
I know this is not part of your change but can you please remove all of these logs about when things are starting and finishing, they are no longer needed

2024-12-18 07:49 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
> +            _logger.LogInformation("Demographic data successfully retrieved.");
I don't know why all of this logging has been added, seems unnecessary to me, but if it is needed can we change some of it to the debug level?

2024-12-18 07:53 UTC, will-larkin-nhs commented
please address the sonarqube issues

2024-12-18 12:19 UTC, Swapnil261188 commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
> +        _logger.LogInformation("[1] Serializing participant data for validation step 1...");
added it as log information earlier to increase the unit test coverage percentage, removed it and added on one debug log statting the serilizing participant data for validation.

2024-12-18 12:21 UTC, Swapnil261188 commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
> +            _logger.LogInformation("Demographic data successfully retrieved.");
All the loggings were being added to increase the unit test coverage percentage, now as per the review comment, updated the debug logs as well.

2024-12-18 12:22 UTC, Swapnil261188 commented on application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
> +        _logger.LogInformation("Starting processing of queue message...");
As asked, Removed the respective log.

2024-12-18 12:23 UTC, Swapnil261188 commented
> please address the sonarqube issues

the SonarQube quality gate is being passed.

2024-12-18 14:10 UTC, will-larkin-nhs requested changes
Is the purpose of this PR just to increase the code coverage percentage? If so, adding more log statements is not the correct way to go about it, you need to either refactor the tests, the code, add new tests, or accept the lower percentage.

2024-12-22 14:20 UTC, Swapnil261188 commented
> Is the purpose of this PR just to increase the code coverage percentage? If so, adding more log statements is not the correct way to go about it, you need to either refactor the tests, the code, add new tests, or accept the lower percentage.

Reverted all the un-necessary logs being added in the addarticipant.cs file and added/refactored the test cases to increase the unit test coverage to 81%

2024-12-23 13:49 UTC, will-larkin-nhs reviewed
The name of the tests should follow the format `MethodName_Scenario_ExpectedResult`, for example `Run_CohortDistributionFails_LogError`. I know the tests in this file do not follow this convention but any new tests should follow this. Further examples of the proper convention can be found in TransformDataServiceTests.cs

2024-12-23 14:08 UTC, Swapnil261188 commented
> The name of the tests should follow the format `MethodName_Scenario_ExpectedResult`, for example `Run_CohortDistributionFails_LogError`. I know the tests in this file do not follow this convention but any new tests should follow this. Further examples of the proper convention can be found in TransformDataServiceTests.cs

Updated the newly added test cases names as per the convention.

2024-12-23 14:33 UTC, will-larkin-nhs commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
There appears to be no assertion in this test. what is it doing?

2024-12-23 14:50 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
it is also logging error, updated the test case name accordingly

2024-12-23 17:00 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
updated the test cases with the respective assertions, unit test coverage now increased to 84%

2024-12-23 17:09 UTC, will-larkin-nhs commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
your test name suggests that the test should only pass when the function logs an error, but your assertion is checking whether or not update eligibility has been called. Is the condition for the test passing that an error is logged or that the function is called?

2024-12-23 17:16 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
this test cases is checking the negative scenario where if the HttpStatusCode is not OK then it should throw an exception. It is not checking the exception log message. If the test case name is creating a confusion , then I have changed the name to Run_ParticipantEligibilityFailure(), just confirm whether it works, or I'll update it to a new name.

2024-12-24 09:23 UTC, will-larkin-nhs commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
Ok so you are testing if the function throws an exception when mark participant as eligible fails? In that case you need to name the test `Run_MarkAsEligibleFails_ThrowException`. However this is not what your test is doing. You are testing whether or not mark as eligible has been called, so you need to update the assertion to check if the function throws an exception.

2024-12-24 09:40 UTC, will-larkin-nhs reviewed
Can you rename the method names to something more descriptive than "handles error correctly". What is the expected behavior for it to handle the error correctly? Also pls address the sonarqube issue

2024-12-24 09:43 UTC, Swapnil261188 commented
> Can you rename the method names to something more descriptive than "handles error correctly". What is the expected behavior for it to handle the error correctly? Also pls address the sonarqube issue

Could you please let me know which method names you are referring to here?
Also, the last sonarqube scan was having 0 issues.

2024-12-24 13:23 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +public async Task Run_ParticipantEligibility_Failure()
updated the test method name and added the exception message assertion as asked.

2024-12-24 13:54 UTC, Joseph2910 submitted a review, later dismissed

2024-12-24 14:05 UTC, Warren-Pitterson commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +    // private readonly ICohortDistributionHandler _cohortDistributionHandler;
Can you remove this comment if it's not needed

2024-12-24 14:05 UTC, Warren-Pitterson commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +
formatting please, remove the whitespace

2024-12-24 14:06 UTC, Warren-Pitterson commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +        // _cohortDistributionHandler = new CohortDistributionHandler(_cohortDistributionLogger.Object, _azureQueueStorageHelper.Object);
If this is not needed remove it please

2024-12-24 14:06 UTC, Warren-Pitterson commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +
whitespace

2024-12-24 14:11 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +    // private readonly ICohortDistributionHandler _cohortDistributionHandler;
done

2024-12-24 14:11 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +
done

2024-12-24 14:11 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +        // _cohortDistributionHandler = new CohortDistributionHandler(_cohortDistributionLogger.Object, _azureQueueStorageHelper.Object);
removed

2024-12-24 14:11 UTC, Swapnil261188 commented on tests/UnitTests/ParticipantManagementServicesTests/AddParticipantTest/AddParticipantTest.cs
> +
done

2024-12-24 14:13 UTC, will-larkin-nhs approved these changes

2024-12-24 14:15 UTC, will-larkin-nhs commented
> > Can you rename the method names to something more descriptive than "handles error correctly". What is the expected behavior for it to handle the error correctly? Also pls address the sonarqube issue
> 
> Could you please let me know which method names you are referring to here? Also, the last sonarqube scan was having 0 issues.

This was a comment for another PR but I accidentally put it on this one which is why I hid it.

2024-12-24 14:18 UTC, merged