feat: new external endpoint for demographic data management
NHSDigital/dtos-cohort-manager pull request #529
Opened 2024-12-23 12:47 UTC by will-larkin-nhs

## Description
New endpoint for the demographic data management function to handle requests from the BI product. Returns just the Primary Care Provider and Preferred Language from the demographic data

## Context
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5398

## Type of changes

- [ ] Refactoring (non-breaking change)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [X] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [X] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-12-23 17:04 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs
> +    public async Task<HttpResponseData> RunExternal([HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req)
Could do with a unit test to cover this

2024-12-27 14:50 UTC, SamRobinson75684 requested changes
not sure I like the name of the file Demographic data function implies it's the data function we use to talk to the database.

2025-01-14 11:06 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs
> +    public async Task<HttpResponseData> RunExternal([HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req)
added

2025-01-14 12:10 UTC, SamRobinson75684 approved these changes

2025-01-14 12:14 UTC, alex-clayton-1 approved these changes

2025-01-14 12:40 UTC, merged