feat/dtoss 3292 data change cohort distribution
NHSDigital/dtos-cohort-manager pull request #82
Opened 2024-07-12 09:27 UTC by Warren-Pitterson

## Description

Renaming of Aggregate to CohortDistribution, Moved Service Provider and Transform Services into Cohort Distribution Service, All associated references for Aggregate have been renamed (interfaces, tests, dockerfiles)

## Context

## Type of changes

- [ x] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ x] I have followed the code style of the project
- [ x] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-07-12 09:44 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs
> +public class AddCohortDistributionDataFunction
This should be `RetrieveCohortDistributionDataFunction`.

There's a few more below that need changing too.

2024-07-12 09:52 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            var SQLGet = $"SELECT PARTICIPANT_ID FROM [dbo].[PARTICIPANT_MANAGEMENT] WHERE NHS_NUMBER = @NHSNumber AND ACTIVE_FLAG = @ActiveFlag "; //WP - Change properties from Participant to Partic
Can we remove this comment?

2024-07-12 09:53 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            var SQLGet = $"SELECT PARTICIPANT_ID FROM [dbo].[PARTICIPANT_MANAGEMENT] WHERE NHS_NUMBER = @NHSNumber AND ACTIVE_FLAG = @ActiveFlag "; //WP - Change properties from Participant to Partic
removed

2024-07-12 09:53 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs
> +public class AddCohortDistributionDataFunction
Changed all references

2024-07-12 10:03 UTC, alex-clayton-1 commented on application/CohortManager/Set-up/database/insert_statement.sql
> +        ,[SCREENING_ACRONYM]
The closing parenthesis needs to be moved to the end of this line

2024-07-12 10:03 UTC, alex-clayton-1 commented on application/CohortManager/Set-up/database/insert_statement.sql
This file contains an INSERT statement on the ELIGIBILITY_CODE_LKP table which has been removed from create_statement.sql

2024-07-12 10:08 UTC, andrewmorris43 commented on application/CohortManager/compose.yaml
> -  # Add Aggregation Service
Minor one, but I think all these functions should sit under the `# Cohort Distribution Service` comment. Just to match how the other services are organised. Something like this:

# Cohort Distribution Service
add-cohort-distribution-data:
...

retrieve-cohort-distribution-data:
...

remove-cohort-distribution-data:
...

transform-data:
...

allocate-service-provider:
...

2024-07-12 10:09 UTC, alex-clayton-1 commented on application/CohortManager/Set-up/database/create_statement.sql
>  END
Is the PARTICIPANT table still needed?

2024-07-12 10:10 UTC, andrewmorris43 commented on tests/AddCohortDistributionDataTests/CohortDistributionDataTests/RemoveCohortDistributionTests.cs
> +﻿namespace NHS.CohortManager.Tests.AddCohortDistributionDataTests;
This should be `RemoveCohortDistributionDataTests`.

2024-07-12 10:20 UTC, andrewmorris43 commented on tests/CaasIntegrationTests/receiveCaasFileTest/ReceiveCaasFileTests.cs
> -        _expectedJson = "{\"Participants\":[{\"RecordType\":\"New\",\"ChangeTimeStamp\":\"20240524153000\",\"SerialChangeNumber\":\"1\",\"NhsNumber\":\"1111111111\",\"SupersededByNhsNumber\":\"\",\"P
I know this has always been like this, but is there a better way to use this expectedJson? It's a pain having to scroll 3 miles right to see what's going on.

Could it be in a separate file maybe, then imported in?

One for another ticket probably.

2024-07-12 10:23 UTC, Warren-Pitterson commented on tests/AddCohortDistributionDataTests/CohortDistributionDataTests/RemoveCohortDistributionTests.cs
> +﻿namespace NHS.CohortManager.Tests.AddCohortDistributionDataTests;
changed

2024-07-12 10:23 UTC, Warren-Pitterson commented on application/CohortManager/compose.yaml
> -  # Add Aggregation Service
changed

2024-07-12 10:23 UTC, Warren-Pitterson commented on application/CohortManager/Set-up/database/insert_statement.sql
> +        ,[SCREENING_ACRONYM]
moved

2024-07-12 10:25 UTC, Warren-Pitterson commented on tests/CaasIntegrationTests/receiveCaasFileTest/ReceiveCaasFileTests.cs
> -        _expectedJson = "{\"Participants\":[{\"RecordType\":\"New\",\"ChangeTimeStamp\":\"20240524153000\",\"SerialChangeNumber\":\"1\",\"NhsNumber\":\"1111111111\",\"SupersededByNhsNumber\":\"\",\"P
definitely is another way to do this, it'll probably need some discussion or another ticket, either way i believe it's outside the scope of this ticket

2024-07-12 10:26 UTC, Warren-Pitterson commented on application/CohortManager/Set-up/database/create_statement.sql
>  END
PARTICIPANT table is still in use

2024-07-12 10:28 UTC, Warren-Pitterson commented on application/CohortManager/Set-up/database/insert_statement.sql
Apologies for this, This is a table that is coming in from another ticket and i was showing someone how it should look. I'll remove as it's on another branch with the table creation

2024-07-12 10:42 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/AddCohortDistributionData.cs
> +        private readonly ICreateResponse _createResponse;
so are we moving all the aggregation data function stuff?

2024-07-12 10:42 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> -        DateTime maxEndDate = DateTime.MaxValue;
don't merge this till after the new changes from the new exception stuff is merged and we'll merge changes form main into this

2024-07-12 10:42 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
>      }
is this all being moved to somewhere else?

2024-07-12 10:48 UTC, alex-clayton-1 commented on application/CohortManager/Set-up/database/create_statement.sql
> +        PARTICIPANT_ID BIGINT not null,
I think we should probably keep IDENTITY(1, 1) here to generate the PARTICIPANT_ID for us

2024-07-12 10:53 UTC, alex-clayton-1 commented on application/CohortManager/Set-up/database/create_statement.sql
>  END
I was under the impression that this table was going to be removed, I don't see any mention of it in the code

2024-07-12 11:05 UTC, Warren-Pitterson commented on application/CohortManager/Set-up/database/create_statement.sql
>  END
you're correct, It's been removed

2024-07-12 11:29 UTC, SamRobinson75684 requested changes
could you make sure to remove the old folders the aggregation functions were in please?

2024-07-12 11:35 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/AddCohortDistributionData.cs
> +        private readonly ICreateResponse _createResponse;
it's been moved

2024-07-12 11:38 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
>      }
yes sir

2024-07-12 11:40 UTC, Warren-Pitterson commented on application/CohortManager/Set-up/database/create_statement.sql
> +        PARTICIPANT_ID BIGINT not null,
Added back in

2024-07-12 12:21 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            " RECORD_UPDATE_DATETIME," +
Remove comma after last column name

2024-07-12 12:21 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            " @recordUpdateDateTime, " +
Remove comma after last value

2024-07-12 12:21 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            "[PARTICIPANT_MANAGEMENT].[RECORD_UPDATE_DATETIME], " +
Remove comma after last column name

2024-07-12 12:51 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            " @recordUpdateDateTime, " +
removed

2024-07-12 12:51 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            "[PARTICIPANT_MANAGEMENT].[RECORD_UPDATE_DATETIME], " +
removed

2024-07-12 14:25 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@reasonForRemovalDate", _databaseHelper.ParseDates(participantData.ReasonForRemovalEffectiveFromDate)},
Need a null check on ReasonForRemovalEffectiveFromDate

2024-07-12 14:25 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@participantId", cohortId},
We shouldn't use cohortId as the participantId parameter. If we don't want to manually set PARTICIPANT_ID in the PARTICIPANT_MANAGEMENT table then we should configure the column as IDENTITY(1, 1)

2024-07-12 14:25 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@screeningId", participantData.ScreeningId},
Need a null check on ScreeningId

2024-07-12 15:00 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@screeningId", participantData.ScreeningId},
Added

2024-07-12 15:00 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@participantId", cohortId},
set to ParticipantId

2024-07-12 15:00 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@reasonForRemovalDate", _databaseHelper.ParseDates(participantData.ReasonForRemovalEffectiveFromDate)},
Added

2024-07-12 15:00 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +                " SET RECORD_UPDATE_DATETIME = @recordEndDateOldRecords, " +
Removed

2024-07-12 15:44 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@participantId", cohortId},
It looks like participantData.ParticipantId will always be an empty string though so the insert will fail since this is for the primary key.

2024-07-13 19:27 UTC, stephhou commented on application/CohortManager/Set-up/database/create_statement.sql
> -CREATE TABLE ELIGIBILITY_CODE_LKP
This ELIGIBILITY_CODE_LKP table needs to stay, it's a new one

2024-07-14 07:51 UTC, stephhou commented on application/CohortManager/src/Functions/CohortDistribution/CohortDistributionService/CohortDistributionService.cs
Has this file been moved or renamed? I can't seem to find it in the new folder structure

2024-07-14 08:25 UTC, stephhou commented on application/CohortManager/Set-up/database/insert_statement.sql
> -INSERT INTO [dbo].[ELIGIBILITY_CODE_LKP]
This needs to be added back in for the new Eligibilty table

2024-07-15 12:19 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@NHSNumber", _databaseHelper.CheckIfNumberNull(participantData.NhsNumber)},
Added

2024-07-15 12:20 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            { "@participantId", cohortId},
Removed Participant Id and set IDENTITY(1,1) attribute on the column

2024-07-15 12:31 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            " @participantId, " +
participantId will need to be removed from here

2024-07-15 12:36 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +            " @participantId, " +
removed

2024-07-15 13:42 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            { "@participantId", cohortId},
Same fixes needed here with participantId and null checks

2024-07-15 14:26 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +            { "@participantId", cohortId},
updated

2024-07-15 14:53 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +        string insertParticipant = "INSERT INTO [dbo].[PARTICIPANT_MANAGEMENT] ( " +
Now that we no longer have an active flag or a record end date, I'm wondering if update participant should still do a new insert into the participant management table or if it should be updating the existing participant. Do you know @stephhou?

2024-07-15 15:04 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +                " WHERE PARTICIPANT_ID = @ParticipantId ",
This command fails since the parameters recordEndDateOldRecords and ParticipantId haven't been supplied although I'm not sure if we even still need the UpdateOldRecords method

2024-07-15 15:41 UTC, stephhou commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +        string insertParticipant = "INSERT INTO [dbo].[PARTICIPANT_MANAGEMENT] ( " +
It should update the existing participant - we can make a separate ticket for that.

2024-07-15 15:47 UTC, stephhou commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +                " WHERE PARTICIPANT_ID = @ParticipantId ",
the UpdateOldRecords method won't be needed as the tables can be updated independently now. Can make a ticket to remove the unneeded methods

2024-07-15 17:32 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +                " WHERE PARTICIPANT_ID = @ParticipantId ",
The method can be removed in the later PR but I'd say the method call should be removed in this one since it causes the update to fail

2024-07-15 17:33 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +                    newParticipantPk = reader.GetInt64(0);
These changes also need to be made for ExecuteCommandAndGetId in UpdateParticipantData

2024-07-15 22:23 UTC, Warren-Pitterson commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
> +                    newParticipantPk = reader.GetInt64(0);
Changed

2024-07-16 09:07 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
> +                " WHERE PARTICIPANT_ID = @ParticipantId ",
just remember if we remove this method we can't mark Participants as eligible or mark Participants as Ineligible without this method as it's used to do both. How do we expect to remove a participant?

2024-07-16 09:45 UTC, alex-clayton-1 approved these changes

2024-07-16 10:02 UTC, SamRobinson75684 approved these changes

2024-07-16 10:05 UTC, merged