feat: adding validation for the record count in the file name
NHSDigital/dtos-cohort-manager pull request #84
Opened 2024-07-15 14:03 UTC by SamTyrrellNHS

…it tests for new function

## Description

Now it checks the record count in the file name against the actual number of records and will stop processing the file if they do not match.

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-07-17 10:27 UTC, MWClayson-NHS requested changes

2024-07-17 10:27 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
> +                throw new FileFormatException("File name record count not equal to actual record count. File name count: " + name + "| Actual count: " + rowNumber);
Please refactor this to avoid using Exceptions as control flow. This should be handled and return in its own function not within in a Catch Block.

2024-07-17 10:27 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
> +            InsertValidationErrorIntoDatabase(name);
This should be awaited. 
_Note: This will need to be changed to use the new exception handling once merged to main_

2024-07-17 10:27 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
> +        var str = name.Remove(name.IndexOf('.'));
This is happening outside of a try catch block and if a file with not "." is read this will throw an exception this is not logged or handled.

2024-07-18 09:51 UTC, SamTyrrellNHS commented on application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
> +        var str = name.Remove(name.IndexOf('.'));
added try catch in calling function do deal with this

2024-07-18 09:51 UTC, SamTyrrellNHS commented on application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
> +            InsertValidationErrorIntoDatabase(name);
added await

2024-07-18 09:51 UTC, SamTyrrellNHS commented on application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
> +                throw new FileFormatException("File name record count not equal to actual record count. File name count: " + name + "| Actual count: " + rowNumber);
changed this to log and return instead of throw exceptions

2024-07-18 10:33 UTC, MWClayson-NHS approved these changes
Please hold off on merging until PR #83 is merged.

2024-07-19 10:04 UTC, merged