feat: add functionality to create cohort distribution function
NHSDigital/dtos-cohort-manager pull request #88
Opened 2024-07-19 08:39 UTC by andrewmorris43

## Description

This PR implements 3 of the 4 functions that should be called from the `CreateCohortDistribution` function and adds unit tests. These functions are as follows:

- Get participant data (this is just a stub for now whilst it is still being implemented)
- Allocate service provider
- Transform participant data
- Add cohort distribution

## Context

[DTOSS-3223](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3223)

## Type of changes

- [x] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [x] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-07-23 13:45 UTC, MWClayson-NHS requested changes
Please review my suggested changes, Happy to discuss over a call if you need any clarification.

2024-07-23 13:45 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +        try
Please change it in to an api call that points to a stub.

2024-07-23 13:45 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
This is a quite a long function which makes things hard to read, please consider breaking down parts of it into individual methods.

2024-07-23 13:45 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +            else error = true;
I think you should just return a badrequest it we hit these error = true's as i think we should stop the processing if we get an error response from any of them.

2024-07-24 12:52 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +            else error = true;
I've made this change thanks.

2024-07-24 14:24 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
> +        try
I have added a stub function called `RetrieveParticipantData`

2024-07-24 15:44 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
This has been refactored into methods that handle the separate tasks.

2024-07-25 09:01 UTC, MWClayson-NHS approved these changes
Looks good to me!

2024-07-25 09:07 UTC, merged