feat: demographic data lookup validation rule
NHSDigital/dtos-cohort-manager pull request #90
Opened 2024-07-22 07:18 UTC by alex-clayton-1

## Description

- Implemented demographics lookup validation rule
- Combined AmendedParticipantMustExist and RemovedParticipantMustExist rules into ParticipantMustExist
- Changed LookupValidation response to BadRequest for when a valid LookupValidationRequestBody is not received 

[DTOSS-3477](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3477)

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-07-23 13:49 UTC, MWClayson-NHS requested changes

2024-07-23 13:49 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs
> +            return _createResponse.CreateHttpResponse(HttpStatusCode.BadRequest, req);
please call the exception service here.

2024-07-25 07:38 UTC, andrewmorris43 approved these changes
There was just a minor fix for the LookupValidation unit tests needed which I've just pushed. Good to merge I think.

2024-07-25 08:21 UTC, MWClayson-NHS approved these changes

2024-07-25 08:22 UTC, merged