feat: transform participant name prefix
NHSDigital/dtos-cohort-manager pull request #95
Opened 2024-07-24 14:52 UTC by will-larkin-nhs

## Description
Implementation for business rules to transform participant name prefix.

## Context
[DTOSS-3346](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3346)

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-07-25 08:03 UTC, andrewmorris43 requested changes
Please can you add some unit tests to cover these new rules. 

There are also some failing tests that need to be fixed.

2024-07-25 08:03 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +        // Set up rules engine
Can the new rules be put into the existing `transformRules.json` file, then we don't need to execute another set of rules just for the name prefix?

2024-07-25 08:34 UTC, MWClayson-NHS commented
Please have a look at the unit tests :)

2024-07-25 08:54 UTC, MWClayson-NHS commented
Please can you also add some test coverage to ensure that the transform rules are covered?

2024-07-25 10:27 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +        // Set up rules engine
they are different business rule sets with different parameters, etc. best to keep them separate

2024-07-25 10:55 UTC, MWClayson-NHS commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> +        _requestBody.Participant.NamePrefix = "ADMIRAL";
You are passing data from DataRow to the test but then hard coding it.

`_requestBody.Participant.NamePrefix = namePrefix`

Another note would be that we can gain more coverage of the rules by having this test take in the namePrefix and expectedNamePrefix output passed into the function and used as part of the assert.

2024-07-25 11:13 UTC, will-larkin-nhs commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> +        _requestBody.Participant.NamePrefix = "ADMIRAL";
covering individual rules is up to the test team I think

2024-07-25 11:25 UTC, andrewmorris43 commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> -    public async Task Run_Should_Not_Transform_Participant_Data_When_NamePrefix_ExceedsMaximumLength_Passes(string namePrefix)
How come you've overwritten this existing test for the `1.NamePrefix.ExceedsMaximumLength` rule? I think this is still a valid test to run.

2024-07-25 11:26 UTC, andrewmorris43 commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> +        _requestBody.Participant.NamePrefix = "ADMIRAL";
I think we need at least one test per new rule

2024-07-25 11:30 UTC, andrewmorris43 commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +        // Set up rules engine
I think they should be in the same file. In the future there will be different transform rules per service provider I believe, so this will mean maintaining multiple files per service provider.

2024-07-25 11:32 UTC, will-larkin-nhs commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> +        _requestBody.Participant.NamePrefix = "ADMIRAL";
there are 45 new rules

2024-07-25 11:39 UTC, will-larkin-nhs commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> -    public async Task Run_Should_Not_Transform_Participant_Data_When_NamePrefix_ExceedsMaximumLength_Passes(string namePrefix)
It is kind of covered in my overwritten test, NamePrefix does not exceed 35, and it is not truncated, if it was truncated, the prefix transformation would not work correctly. and again, there are going to be many more transformation rules, so I think whether or not each rule works correctly on that level will be covered by the test team

2024-07-25 13:00 UTC, MWClayson-NHS commented on application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
> +        // Set up rules engine
Leave it as is for the moment, we will need to refactor some of this once we have a better understanding of how we will handle multiple different rule sets per service provider / screening service.

Building out the execution of the rule sets with more reusable code should be the end goal.

2024-07-25 13:03 UTC, MWClayson-NHS commented on tests/TransformDataServiceTests/TransformDataServiceTests.cs
> +        _requestBody.Participant.NamePrefix = "ADMIRAL";
Cherry pick three or four they are mostly functionally the same. we have them all in the same test method but with different data rows. Also i notice some rules are using == and some are using .StartsWith both of these types should be covered by those cherry picked tests.

2024-07-29 09:31 UTC, MWClayson-NHS approved these changes
Looks good to me!

2024-07-29 09:32 UTC, merged